
package auction.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.11
 * Tue Feb 17 15:07:36 EET 2015
 * Generated source version: 2.7.11
 */

@XmlRootElement(name = "newBidResponse", namespace = "http://service.auction/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "newBidResponse", namespace = "http://service.auction/")

public class NewBidResponse {

    @XmlElement(name = "return")
    private auction.service.BidFromService _return;

    public auction.service.BidFromService getReturn() {
        return this._return;
    }

    public void setReturn(auction.service.BidFromService new_return)  {
        this._return = new_return;
    }

}

