
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package auction.service;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-02-17T15:07:38.239+02:00
 * Generated source version: 2.7.11
 * 
 */
public class AuctionSEIClient {

    public static void main(String[] args) throws Exception {
        QName serviceName = new QName("http://service.auction/", "AuctionService");
        QName portName = new QName("http://service.auction/", "AuctionPort");

        Service service = Service.create(serviceName);
        service.addPort(portName, SOAPBinding.SOAP11HTTP_BINDING,
                        "http://localhost:9090/AuctionPort"); 
        auction.service.AuctionSEI client = service.getPort(portName,  auction.service.AuctionSEI.class);
        
        // Insert code to invoke methods on the client here
    }

}