package auction.service.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-01-07T16:09:27.356+02:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://service.auction/", name = "AuctionSEI")
@XmlSeeAlso({ObjectFactory.class})
public interface AuctionSEI {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "cencelTheLot", targetNamespace = "http://service.auction/", className = "auction.service.client.CencelTheLot")
    @WebMethod
    @ResponseWrapper(localName = "cencelTheLotResponse", targetNamespace = "http://service.auction/", className = "auction.service.client.CencelTheLotResponse")
    public boolean cencelTheLot(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "newLot", targetNamespace = "http://service.auction/", className = "auction.service.client.NewLot")
    @WebMethod
    @ResponseWrapper(localName = "newLotResponse", targetNamespace = "http://service.auction/", className = "auction.service.client.NewLotResponse")
    public boolean newLot(
        @WebParam(name = "arg0", targetNamespace = "")
        auction.service.client.LotFromService arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getBidsOnLot", targetNamespace = "http://service.auction/", className = "auction.service.client.GetBidsOnLot")
    @WebMethod
    @ResponseWrapper(localName = "getBidsOnLotResponse", targetNamespace = "http://service.auction/", className = "auction.service.client.GetBidsOnLotResponse")
    public java.util.List<auction.service.client.BidFromService> getBidsOnLot(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "registration", targetNamespace = "http://service.auction/", className = "auction.service.client.Registration")
    @WebMethod
    @ResponseWrapper(localName = "registrationResponse", targetNamespace = "http://service.auction/", className = "auction.service.client.RegistrationResponse")
    public int registration(
        @WebParam(name = "arg0", targetNamespace = "")
        auction.service.client.UserFrowService arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getLots", targetNamespace = "http://service.auction/", className = "auction.service.client.GetLots")
    @WebMethod
    @ResponseWrapper(localName = "getLotsResponse", targetNamespace = "http://service.auction/", className = "auction.service.client.GetLotsResponse")
    public java.util.List<auction.service.client.LotFromService> getLots();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getLotInfo", targetNamespace = "http://service.auction/", className = "auction.service.client.GetLotInfo")
    @WebMethod
    @ResponseWrapper(localName = "getLotInfoResponse", targetNamespace = "http://service.auction/", className = "auction.service.client.GetLotInfoResponse")
    public auction.service.client.LotFromService getLotInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "authentication", targetNamespace = "http://service.auction/", className = "auction.service.client.Authentication")
    @WebMethod
    @ResponseWrapper(localName = "authenticationResponse", targetNamespace = "http://service.auction/", className = "auction.service.client.AuthenticationResponse")
    public auction.service.client.UserFrowService authentication(
        @WebParam(name = "arg0", targetNamespace = "")
        auction.service.client.UserFrowService arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "newBid", targetNamespace = "http://service.auction/", className = "auction.service.client.NewBid")
    @WebMethod
    @ResponseWrapper(localName = "newBidResponse", targetNamespace = "http://service.auction/", className = "auction.service.client.NewBidResponse")
    public boolean newBid(
        @WebParam(name = "arg0", targetNamespace = "")
        auction.service.client.BidFromService arg0
    );
}
