
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package auction.service.client;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-02-14T17:19:32.778+02:00
 * Generated source version: 2.7.11
 * 
 */

@javax.jws.WebService(
                      serviceName = "AuctionService",
                      portName = "AuctionPort",
                      targetNamespace = "http://service.auction/",
                      wsdlLocation = "http://localhost:8080/auction/services/AuctionPort?wsdl",
                      endpointInterface = "auction.service.client.AuctionSEI")
                      
public class AuctionSEIImpl implements AuctionSEI {

    private static final Logger LOG = Logger.getLogger(AuctionSEIImpl.class.getName());

    /* (non-Javadoc)
     * @see auction.service.client.AuctionSEI#cencelTheLot(int  arg0 )*
     */
    public auction.service.client.LotFromService cencelTheLot(int arg0) { 
        LOG.info("Executing operation cencelTheLot");
        System.out.println(arg0);
        try {
            auction.service.client.LotFromService _return = new auction.service.client.LotFromService();
            _return.setCode("Code-407569558");
            _return.setDescription("Description-1018910798");
            _return.setFinish("Finish1587052280");
            _return.setName("Name-1617665010");
            _return.setOwner("Owner-426321940");
            _return.setPrice("Price1259472626");
            _return.setState("State-916174533");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see auction.service.client.AuctionSEI#newLot(auction.service.client.LotFromService  arg0 )*
     */
    public auction.service.client.LotFromService newLot(auction.service.client.LotFromService arg0) { 
        LOG.info("Executing operation newLot");
        System.out.println(arg0);
        try {
            auction.service.client.LotFromService _return = new auction.service.client.LotFromService();
            _return.setCode("Code-1042286315");
            _return.setDescription("Description2024503473");
            _return.setFinish("Finish2062963102");
            _return.setName("Name2129764080");
            _return.setOwner("Owner-1095009183");
            _return.setPrice("Price324663879");
            _return.setState("State914023992");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see auction.service.client.AuctionSEI#getBidsOnLot(int  arg0 )*
     */
    public java.util.List<auction.service.client.BidFromService> getBidsOnLot(int arg0) { 
        LOG.info("Executing operation getBidsOnLot");
        System.out.println(arg0);
        try {
            java.util.List<auction.service.client.BidFromService> _return = new java.util.ArrayList<auction.service.client.BidFromService>();
            auction.service.client.BidFromService _returnVal1 = new auction.service.client.BidFromService();
            _returnVal1.setBid("Bid-1434955735");
            _returnVal1.setBidder("Bidder1485382554");
            _returnVal1.setDate("Date1791156831");
            _returnVal1.setLot("Lot-1430927900");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see auction.service.client.AuctionSEI#registration(auction.service.client.UserFrowService  arg0 )*
     */
    public int registration(auction.service.client.UserFrowService arg0) { 
        LOG.info("Executing operation registration");
        System.out.println(arg0);
        try {
            int _return = 1020237851;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see auction.service.client.AuctionSEI#getLots(*
     */
    public java.util.List<auction.service.client.LotFromService> getLots() { 
        LOG.info("Executing operation getLots");
        try {
            java.util.List<auction.service.client.LotFromService> _return = new java.util.ArrayList<auction.service.client.LotFromService>();
            auction.service.client.LotFromService _returnVal1 = new auction.service.client.LotFromService();
            _returnVal1.setCode("Code1187802599");
            _returnVal1.setDescription("Description1909524638");
            _returnVal1.setFinish("Finish35335863");
            _returnVal1.setName("Name-67771375");
            _returnVal1.setOwner("Owner-794226217");
            _returnVal1.setPrice("Price841988277");
            _returnVal1.setState("State1029183027");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see auction.service.client.AuctionSEI#getLotInfo(int  arg0 )*
     */
    public auction.service.client.LotFromService getLotInfo(int arg0) { 
        LOG.info("Executing operation getLotInfo");
        System.out.println(arg0);
        try {
            auction.service.client.LotFromService _return = new auction.service.client.LotFromService();
            _return.setCode("Code-1948674653");
            _return.setDescription("Description147350916");
            _return.setFinish("Finish-1581751890");
            _return.setName("Name402343954");
            _return.setOwner("Owner279917607");
            _return.setPrice("Price-1955945227");
            _return.setState("State-1321507191");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see auction.service.client.AuctionSEI#authentication(auction.service.client.UserFrowService  arg0 )*
     */
    public auction.service.client.UserFrowService authentication(auction.service.client.UserFrowService arg0) { 
        LOG.info("Executing operation authentication");
        System.out.println(arg0);
        try {
            auction.service.client.UserFrowService _return = new auction.service.client.UserFrowService();
            _return.setFname("Fname1607150914");
            _return.setId("Id1593098598");
            _return.setLname("Lname467385028");
            _return.setLogin("Login1923933191");
            _return.setPassword("Password-1493008591");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see auction.service.client.AuctionSEI#newBid(auction.service.client.BidFromService  arg0 )*
     */
    public auction.service.client.BidFromService newBid(auction.service.client.BidFromService arg0) { 
        LOG.info("Executing operation newBid");
        System.out.println(arg0);
        try {
            auction.service.client.BidFromService _return = new auction.service.client.BidFromService();
            _return.setBid("Bid-1559681646");
            _return.setBidder("Bidder668561152");
            _return.setDate("Date-872972348");
            _return.setLot("Lot210660170");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
