
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package auction.service.client;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-02-17T15:08:08.713+02:00
 * Generated source version: 2.7.11
 * 
 */

@javax.jws.WebService(
                      serviceName = "AuctionService",
                      portName = "AuctionPort",
                      targetNamespace = "http://service.auction/",
                      wsdlLocation = "http://localhost:8080/auction/services/AuctionPort?wsdl",
                      endpointInterface = "auction.service.client.AuctionSEI")
                      
public class AuctionSEIImpl implements AuctionSEI {

    private static final Logger LOG = Logger.getLogger(AuctionSEIImpl.class.getName());

    /* (non-Javadoc)
     * @see auction.service.client.AuctionSEI#cencelTheLot(int  arg0 )*
     */
    public void cencelTheLot(int arg0) { 
        LOG.info("Executing operation cencelTheLot");
        System.out.println(arg0);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see auction.service.client.AuctionSEI#newLot(auction.service.client.LotFromService  arg0 )*
     */
    public auction.service.client.LotFromService newLot(auction.service.client.LotFromService arg0) { 
        LOG.info("Executing operation newLot");
        System.out.println(arg0);
        try {
            auction.service.client.LotFromService _return = new auction.service.client.LotFromService();
            _return.setCode("Code-492704703");
            _return.setDescription("Description1129055851");
            _return.setFinish("Finish-2117232927");
            _return.setName("Name-1185547787");
            _return.setOwner("Owner1476933315");
            _return.setPrice("Price-989501841");
            _return.setState("State-1899286853");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see auction.service.client.AuctionSEI#getBidsOnLot(int  arg0 )*
     */
    public java.util.List<auction.service.client.BidFromService> getBidsOnLot(int arg0) { 
        LOG.info("Executing operation getBidsOnLot");
        System.out.println(arg0);
        try {
            java.util.List<auction.service.client.BidFromService> _return = new java.util.ArrayList<auction.service.client.BidFromService>();
            auction.service.client.BidFromService _returnVal1 = new auction.service.client.BidFromService();
            _returnVal1.setBid("Bid1357168539");
            _returnVal1.setBidder("Bidder802575280");
            _returnVal1.setDate("Date-1511106749");
            _returnVal1.setLot("Lot-1205049891");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see auction.service.client.AuctionSEI#registration(auction.service.client.UserFrowService  arg0 )*
     */
    public int registration(auction.service.client.UserFrowService arg0) { 
        LOG.info("Executing operation registration");
        System.out.println(arg0);
        try {
            int _return = 1695957183;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see auction.service.client.AuctionSEI#getLots(*
     */
    public java.util.List<auction.service.client.LotFromService> getLots() { 
        LOG.info("Executing operation getLots");
        try {
            java.util.List<auction.service.client.LotFromService> _return = new java.util.ArrayList<auction.service.client.LotFromService>();
            auction.service.client.LotFromService _returnVal1 = new auction.service.client.LotFromService();
            _returnVal1.setCode("Code1144615371");
            _returnVal1.setDescription("Description1785205832");
            _returnVal1.setFinish("Finish714503732");
            _returnVal1.setName("Name-1301730282");
            _returnVal1.setOwner("Owner576656421");
            _returnVal1.setPrice("Price-1422731123");
            _returnVal1.setState("State-1942728424");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see auction.service.client.AuctionSEI#getLotInfo(int  arg0 )*
     */
    public auction.service.client.LotFromService getLotInfo(int arg0) { 
        LOG.info("Executing operation getLotInfo");
        System.out.println(arg0);
        try {
            auction.service.client.LotFromService _return = new auction.service.client.LotFromService();
            _return.setCode("Code1334296082");
            _return.setDescription("Description-447799581");
            _return.setFinish("Finish-395483587");
            _return.setName("Name-567966803");
            _return.setOwner("Owner-1897867400");
            _return.setPrice("Price-153916347");
            _return.setState("State-1816063656");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see auction.service.client.AuctionSEI#authentication(auction.service.client.UserFrowService  arg0 )*
     */
    public auction.service.client.UserFrowService authentication(auction.service.client.UserFrowService arg0) { 
        LOG.info("Executing operation authentication");
        System.out.println(arg0);
        try {
            auction.service.client.UserFrowService _return = new auction.service.client.UserFrowService();
            _return.setFname("Fname1489796493");
            _return.setId("Id1990420784");
            _return.setLname("Lname1205153251");
            _return.setLogin("Login-1741209178");
            _return.setPassword("Password2036866467");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see auction.service.client.AuctionSEI#newBid(auction.service.client.BidFromService  arg0 )*
     */
    public auction.service.client.BidFromService newBid(auction.service.client.BidFromService arg0) { 
        LOG.info("Executing operation newBid");
        System.out.println(arg0);
        try {
            auction.service.client.BidFromService _return = new auction.service.client.BidFromService();
            _return.setBid("Bid434391387");
            _return.setBidder("Bidder156802616");
            _return.setDate("Date1552981991");
            _return.setLot("Lot398371161");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
