
package auction.service.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-02-17T15:08:08.649+02:00
 * Generated source version: 2.7.11
 * 
 */
public final class AuctionSEI_AuctionPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.auction/", "AuctionService");

    private AuctionSEI_AuctionPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AuctionService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        AuctionService ss = new AuctionService(wsdlURL, SERVICE_NAME);
        AuctionSEI port = ss.getAuctionPort();  
        
        {
        System.out.println("Invoking cencelTheLot...");
        int _cencelTheLot_arg0 = 1136027615;
        port.cencelTheLot(_cencelTheLot_arg0);


        }
        {
        System.out.println("Invoking newLot...");
        auction.service.client.LotFromService _newLot_arg0 = new auction.service.client.LotFromService();
        _newLot_arg0.setCode("Code-353966197");
        _newLot_arg0.setDescription("Description1112838211");
        _newLot_arg0.setFinish("Finish384484550");
        _newLot_arg0.setName("Name1066469788");
        _newLot_arg0.setOwner("Owner-1266244517");
        _newLot_arg0.setPrice("Price-1196083245");
        _newLot_arg0.setState("State62243523");
        auction.service.client.LotFromService _newLot__return = port.newLot(_newLot_arg0);
        System.out.println("newLot.result=" + _newLot__return);


        }
        {
        System.out.println("Invoking getBidsOnLot...");
        int _getBidsOnLot_arg0 = 1618093171;
        java.util.List<auction.service.client.BidFromService> _getBidsOnLot__return = port.getBidsOnLot(_getBidsOnLot_arg0);
        System.out.println("getBidsOnLot.result=" + _getBidsOnLot__return);


        }
        {
        System.out.println("Invoking registration...");
        auction.service.client.UserFrowService _registration_arg0 = new auction.service.client.UserFrowService();
        _registration_arg0.setFname("Fname-865480996");
        _registration_arg0.setId("Id-330455947");
        _registration_arg0.setLname("Lname-155395674");
        _registration_arg0.setLogin("Login557622104");
        _registration_arg0.setPassword("Password888546031");
        int _registration__return = port.registration(_registration_arg0);
        System.out.println("registration.result=" + _registration__return);


        }
        {
        System.out.println("Invoking getLots...");
        java.util.List<auction.service.client.LotFromService> _getLots__return = port.getLots();
        System.out.println("getLots.result=" + _getLots__return);


        }
        {
        System.out.println("Invoking getLotInfo...");
        int _getLotInfo_arg0 = 580336076;
        auction.service.client.LotFromService _getLotInfo__return = port.getLotInfo(_getLotInfo_arg0);
        System.out.println("getLotInfo.result=" + _getLotInfo__return);


        }
        {
        System.out.println("Invoking authentication...");
        auction.service.client.UserFrowService _authentication_arg0 = new auction.service.client.UserFrowService();
        _authentication_arg0.setFname("Fname327971289");
        _authentication_arg0.setId("Id2117355062");
        _authentication_arg0.setLname("Lname-495053909");
        _authentication_arg0.setLogin("Login-466851889");
        _authentication_arg0.setPassword("Password-1289217974");
        auction.service.client.UserFrowService _authentication__return = port.authentication(_authentication_arg0);
        System.out.println("authentication.result=" + _authentication__return);


        }
        {
        System.out.println("Invoking newBid...");
        auction.service.client.BidFromService _newBid_arg0 = new auction.service.client.BidFromService();
        _newBid_arg0.setBid("Bid-1166143177");
        _newBid_arg0.setBidder("Bidder-1047051444");
        _newBid_arg0.setDate("Date-1940982358");
        _newBid_arg0.setLot("Lot-374261374");
        auction.service.client.BidFromService _newBid__return = port.newBid(_newBid_arg0);
        System.out.println("newBid.result=" + _newBid__return);


        }

        System.exit(0);
    }

}
